import {defineField, defineType} from 'sanity'
const refs = (name, title, to, min, max) => defineField({name, title, type: 'array', of: [{type: 'reference', to: [{type: to}]}], validation: (Rule) => Rule.min(min).max(max)})
export const homePage = defineType({name: 'v4.homePage', title: 'v4 Početna', type: 'document', fields: [
  defineField({name: 'seo', title: 'SEO', type: 'v4.seo'}),
  defineField({name: 'hero', title: 'Hero', type: 'object', fields: [defineField({name: 'heading', title: 'Naslov', type: 'string'}), defineField({name: 'body', title: 'Tekst', type: 'text'}), defineField({name: 'ctaLabel', title: 'CTA', type: 'string'}), defineField({name: 'fallbackImage', title: 'Rezervna slika', type: 'v4.editorialImage'})]}),
  defineField({name: 'servicesIntro', title: 'Usluge', type: 'object', fields: [defineField({name: 'heading', title: 'Naslov', type: 'string'}), refs('services', 'Usluge', 'v4.service', 4, 4)]}),
  defineField({name: 'mission', title: 'Misija', type: 'object', fields: [defineField({name: 'heading', title: 'Naslov', type: 'string'}), defineField({name: 'body', title: 'Tekst', type: 'text'}), defineField({name: 'quote', title: 'Citat', type: 'text'}), defineField({name: 'quoteAuthor', title: 'Autor', type: 'string'}), defineField({name: 'images', title: 'Slike', type: 'array', of: [{type: 'v4.editorialImage'}]}), defineField({name: 'statistics', title: 'Statistike', type: 'array', of: [{type: 'v4.statisticCard'}]})]}),
  defineField({name: 'testimonialShowcase', title: 'Preporuke', type: 'object', fields: [defineField({name: 'heading', title: 'Naslov', type: 'string'}), defineField({name: 'body', title: 'Tekst', type: 'text'}), refs('testimonials', 'Preporuke', 'v4.testimonial', 0, 12), defineField({name: 'wordmarks', title: 'Pokretne oznake', type: 'array', of: [{type: 'string'}]})]}),
  defineField({name: 'aboutTeaser', title: 'O nama', type: 'object', fields: [defineField({name: 'eyebrow', title: 'Nadnaslov', type: 'string'}), defineField({name: 'heading', title: 'Naslov', type: 'string'}), defineField({name: 'body', title: 'Tekst', type: 'text'}), defineField({name: 'media', title: 'Slika', type: 'v4.editorialImage'}), defineField({name: 'ctaLabel', title: 'CTA', type: 'string'})]}),
  defineField({name: 'locationsTeaser', title: 'Lokacije', type: 'object', fields: [defineField({name: 'heading', title: 'Naslov', type: 'string'}), defineField({name: 'body', title: 'Tekst', type: 'text'}), refs('locations', 'Lokacije', 'v4.location', 0, 10)]}),
  defineField({name: 'faq', title: 'FAQ', type: 'object', fields: [defineField({name: 'heading', title: 'Naslov', type: 'string'}), refs('items', 'FAQ stavke', 'v4.faqItem', 0, 20)]}),
]})
