import {Link} from 'react-router-dom'
import FigmaArrow from '../ui/FigmaArrow.jsx'

const missionImage = '/assets/home/mission-containers.jpg'
const certificateImage = '/assets/home/client-business-excellent.png'
const statisticImage = '/assets/home/mission-speed.jpg'
const truckIcon = '/assets/home/mission-truck-icon.png'
const cultureAmpLogo = '/assets/home/client-culture-amp.svg'

function MissionMediaGrid({mission}) {
  return <div className="mt-10 grid gap-4 lg:relative lg:h-[698px] lg:block">
    <div className="overflow-hidden rounded-input lg:absolute lg:left-0 lg:top-0 lg:h-[580px] lg:w-[458px]"><img alt="Narandžasti transportni kontejneri" className="h-full w-full object-cover" decoding="async" height="1159" loading="lazy" src={missionImage} width="869" /></div>
    <div className="flex min-h-[102px] items-center gap-[21px] rounded-input bg-white px-[22px] py-[13px] lg:absolute lg:left-0 lg:top-[596px] lg:h-[102px] lg:w-[458px]"><div className="h-[72px] w-[72px] shrink-0 overflow-hidden"><img alt="" aria-hidden="true" className="h-[72px] w-[180px] max-w-none object-contain object-left" decoding="async" height="383" loading="lazy" src={certificateImage} width="960" /></div><div><p className="text-[24px] font-semibold leading-[1.3] tracking-[-0.01em]">Excellent</p><p className="text-[20px] leading-[1.3] tracking-[-0.01em]">Privredna komora Srbije</p></div></div>
    <article className="flex min-h-[344px] flex-col rounded-input bg-white p-6 lg:absolute lg:left-[474px] lg:top-0 lg:h-[344px] lg:w-[520px]"><div aria-hidden="true" className="h-[25px] overflow-hidden text-[80px] leading-[.65]">&ldquo;</div><blockquote className="mt-5 max-w-[472px] text-[24px] italic leading-[1.3] tracking-[-0.01em]">{mission.quote}</blockquote><p className="mt-auto text-[15px] leading-[1.4]"><span className="font-medium">{mission.quoteAuthor}, </span><span className="italic text-source-placeholder">{mission.quoteRole}</span></p></article>
    <article className="relative min-h-[344px] overflow-hidden rounded-input bg-brand-deep-green text-white lg:absolute lg:left-[1010px] lg:top-0 lg:h-[344px] lg:w-[286px]"><img alt="Kamion u pokretu" className="absolute inset-0 h-full w-full object-cover" decoding="async" height="690" loading="lazy" src={statisticImage} width="460" /><div className="absolute inset-0 bg-black/10" /><div className="relative p-6"><p className="text-[41px] font-semibold leading-[1.3] tracking-[-0.01em]">{mission.statisticValue}</p><p className="text-[16px] font-medium leading-[1.3] tracking-[-0.01em]">{mission.statisticLabel}</p></div><div aria-hidden="true" className="absolute bottom-6 left-6 flex items-center gap-3"><img alt="" className="h-[16px] w-auto" src={cultureAmpLogo} /><span className="font-serif text-[18px] font-semibold leading-none">●◐ Medium</span></div></article>
    <article className="flex min-h-[338px] flex-col rounded-input bg-white p-6 lg:absolute lg:left-[474px] lg:top-[360px] lg:h-[338px] lg:w-[425px]"><p className="text-[41px] font-semibold leading-[1.3] tracking-[-0.01em]">{mission.commitmentValue}</p><h3 className="mt-2 text-[16px] font-semibold leading-[1.3] tracking-[0.02em]">{mission.commitmentTitle}</h3><p className="mt-[11px] max-w-[377px] text-[15px] leading-[1.4] tracking-[-0.01em]">{mission.commitmentBody}</p><Link className="mt-auto inline-flex h-[43px] w-fit items-center gap-2.5 rounded-button bg-brand-ink px-[18px] text-[15px] text-white" to="/o-nama"><span>{mission.commitmentCta}</span><span className="grid size-[19px] place-items-center rounded-full bg-brand-signal-yellow"><FigmaArrow className="size-[9px]" direction="dark" /></span></Link></article>
    <article className="relative flex min-h-[338px] flex-col justify-end overflow-hidden rounded-input bg-brand-logistics-green p-6 text-white lg:absolute lg:left-[915px] lg:top-[360px] lg:h-[338px] lg:w-[381px]"><span className="absolute left-6 top-6 grid size-[55px] place-items-center rounded-full bg-brand-bright-green"><img alt="" aria-hidden="true" className="size-[31px]" src={truckIcon} /></span><p className="max-w-[333px] text-[24px] leading-[1.3] tracking-[-0.01em]">{mission.statement}</p></article>
  </div>
}

export default MissionMediaGrid
