import hero from './hero'
import about from './about'
import services from './services'
import locations from './locations'
import contact from './contact'
import partners from './partners'
import footer from './footer'
import {seo} from './objects/seo'
import {editorialImage} from './objects/editorialImage'
import {cta} from './objects/cta'
import {navigationItem} from './objects/navigationItem'
import {company} from './objects/company'
import {contactInfo} from './objects/contactInfo'
import {socials} from './objects/socials'
import {highlightCard} from './objects/highlightCard'
import {processStep} from './objects/processStep'
import {statisticCard} from './objects/statisticCard'
import {workingHours} from './objects/workingHours'
import {formLabels} from './objects/formLabels'
import {serviceOption} from './objects/serviceOption'
import {siteSettings} from './documents/siteSettings'
import {homePage} from './documents/homePage'
import {aboutPage} from './documents/aboutPage'
import {servicesPage} from './documents/servicesPage'
import {contactPage} from './documents/contactPage'
import {service} from './documents/service'
import {location} from './documents/location'
import {partner} from './documents/partner'
import {teamMember} from './documents/teamMember'
import {testimonial} from './documents/testimonial'
import {faqItem} from './documents/faqItem'
import {legal} from './documents/legal'

export const legacySchemaTypes = [hero, about, services, contact, locations, partners, footer]
export const v4SchemaTypes = [seo, editorialImage, cta, navigationItem, company, contactInfo, socials, highlightCard, processStep, statisticCard, workingHours, formLabels, serviceOption, siteSettings, homePage, aboutPage, servicesPage, contactPage, service, location, partner, teamMember, testimonial, faqItem, legal]
export const schemaTypes = [...legacySchemaTypes, ...v4SchemaTypes]
